spring:
  application:
    name: AI_budgeting
  docker:
    compose:
      enabled: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/budget-db
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
          response-format:
            type: text
      audio:
        speech:
          options:
            model: gpt-4o-mini-tts
            voice: nova
            speed: 1.1
            response-format: mp3
        transcription:
          options:
            model: whisper-1
            language: pt
            temperature: 0
            response-format: text
            prompt: |
              Audio em portugues brasileiro.
              Audio tem descricao de gastos financeiros
              As frases normalmente contem:
              - um valor em reais(numero + "reais")
              - uma ação (gastei, paguei, comprei)
              - um local ou estabelecimento (mercado, farmacio, restaurante, etc.
logging:
  level:
    org.springframework.ai: DEBUG



